# Auto-generated CMakeLists.txt for agnocast_bridge_plugins
# Generated by: ros2 agnocast generate-bridge-plugins

cmake_minimum_required(VERSION 3.14)

set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")

project(agnocast_bridge_plugins)

set(CMAKE_UNITY_BUILD ON)

if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 17)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    option(ENABLE_TIME_TRACE "Enable clang -ftime-trace" ON)
    
    if(ENABLE_TIME_TRACE)
        add_compile_options("-ftime-trace")
        message(STATUS "Clang ftime-trace is enabled. Profile files.")
    endif()
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(agnocastlib REQUIRED)
@[for pkg in package_names]
find_package(@(pkg) REQUIRED)
@[end for]

# --- 全てのソースファイルを1つのライブラリにまとめる ---
add_library(${PROJECT_NAME} SHARED
@[for msg_type in message_types]
  src/pubsub_bridge_plugin_@(msg_type.replace('/', '_')).cpp
@[end for]
@[for srv_type in service_types]
  src/service_bridge_plugin_@(srv_type.replace('/', '_')).cpp
@[end for]
)

target_link_libraries(${PROJECT_NAME} agnocastlib::agnocast)

# package_names には重複のない依存パッケージの一覧がすでに入っているので、そのまま展開します
ament_target_dependencies(${PROJECT_NAME}
  rclcpp
@[for pkg in package_names]
  @(pkg)
@[end for]
)

install(TARGETS ${PROJECT_NAME}
  DESTINATION lib/${PROJECT_NAME})

# Use precompiled headers to speed up build (requires CMake >= 3.16)
# ターゲットが1つになったため、PCH（プリコンパイル済みヘッダー）の再利用ロジックが不要になりシンプルになります
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.16")
  set_target_properties(${PROJECT_NAME} PROPERTIES DEFINE_SYMBOL "AGNOCAST_BRIDGE_PLUGIN_EXPORTS")
  target_precompile_headers(${PROJECT_NAME} PRIVATE
    <agnocast/agnocast.hpp>
    <rclcpp/rclcpp.hpp>
    <utility>)
endif()

ament_package()
